### ISSUE TITLE
Can not build it on ubuntu 14.04

### ISSUE THREAD

**Issue by gapry** [jmwoehr/rsL4#2]
It occurs the following error message after I run `build.sh`

`HEAD is now at 8eb7034 calibre: update from 2.20.0 to 2.21.0`
`HEAD is now at 8eb7034... calibre: update from 2.20.0 to 2.21.0`
`~/Workspaces/rsL4`
`warning: Nix search path entry ~/Workspaces/woehr-nixpkgs’ does not exist, ignoring`
`error: attribute ‘gcc-armv7l-unknown-linux-gnueabihf’ missing, at ~/Workspaces/rsL4/default.nix:47:20
(use ‘--show-trace’ to show detailed location information)`

It seems It can't find toolchain via pkg, so I try to replace the prefix such as  `arm-none-linux-gnueabi-` or `gcc-arm-linux-gnueab-`,  but it doesn't work.

Any suggestion ?

**Comment by woehr** [comment]
The problem is that I was using my fork of nixpkgs which has some support for building the cross-compiler toolchain, but I didn't add that modification to the build script. I poked around a bit and arch linux arm updated the cross compiler config files, so that doesn't work either.

I'm happy to answer any questions you have about what I was working on here, but I'm not actively doing any development on it.

**Comment by gapry** [comment]
Thanks for your reply.

I need to read the Nix document if I need to fix it,  is it true?

**Comment by woehr** [comment]
If you are unfamiliar with nix it might be easiest to install rustc and the cross gcc manually and look at default.nix in the root directory to see how various things were built.
